Repository gureums/Game-Stream-Trends, pull requests merged in 2025-01, with the labels that each got.

#91 Feature/web deploy
  src/deploy/deploy_back.sh
  src/deploy/deploy_front.sh
  src/deploy/gst
Labels: dev-setup, webserver

#94 Feature/web back
  .github/workflows/back-deploy.yml
  .gitignore
  requirements.txt
  src/backend/README.md
  src/backend/main.py
  src/backend/requirements.txt
  src/backend/routes/__init__.py
  src/backend/routes/apis.py
  src/backend/utils/__init__.py
  src/backend/utils/dbclient.py
Labels: webserver

#92 [feat] 데이터 정제하는 Glue Job 코드 추가
  scripts/all/glue_job/gureum_s3_to_redshift.py
  scripts/steam/glue_job/transform_discounts_in_use.py
  scripts/steam/glue_job/transform_image_from_details.py
  scripts/steam/glue_job/transform_players_backfilling.py
  scripts/steam/glue_job/transform_players_in_use.py
  scripts/steam/glue_job/transform_review_metas_backfilling.py
  scripts/steam/glue_job/transform_review_metas_in_use.py
  scripts/twitch/glue_job/transform_streams.py
  scripts/twitch/glue_job/transform_streams_backfilling.py
  scripts/twitch/glue_job/transform_top_categories.py
  scripts/twitch/glue_job/transform_top_categories_backfilling.py
  scripts/youtube/glue_job/transform_videos.py
  scripts/youtube/glue_job/transform_videos_backfilling.py
Labels: infra, data, modeling

#96 [Chore] remove unnecessary files
  dags/.gitkeep
  dags/all/silver_s3_to_redshift_v2.py
  dags/for-all/silver_s3_to_redshift.py
  dags/for-all/silver_s3_to_redshift_full_load.py
  dags/for-all/table_metadata.py
  dags/steam/players_full_refresh_v3.py
  dags/steam/steam_silver_to_redshift.py
  dags/steam/steam_silver_to_redshift_v2.py
  dags/steam/steam_tables.py
  dags/twitch/twitch_silver_to_redshift.py
  dags/youtube/youtube_silver.py
  dags/youtube/youtube_silver_redshift.py
  dags/youtube/youtube_silver_redshift_test.py
  scripts/all/glue_job/gureum_s3_to_redshift.py
  scripts/steam_news/glue_job/news_succeeded.py
  scripts/steam_news/glue_job/news_succeeded_not_file.py
  scripts/steam_news/test.py
Labels: refactoring
